.TH taptempo 1
.SH NAME
taptempo \- a command line tap tempo
.SH SYNOPSIS
.B taptempo
.SH DESCRIPTION
Hit the 
.B enter key 
with style and the program prints the corresponding number of beats per minute (bpm).
.PP
Use this program to quickly find the tempo of a song.
.PP
Type 
.B q
then 
.B enter key
to quit the program.
.SH OPTIONS
No options
.SH AUTHOR
Francois Mazen <francois@mzf.fr>
